sudo:                      true

language:                  python
cache:
  directories:
    - $HOME/virtualenv/
    - $HOME/.R
    - $HOME/Library


matrix:
    include:
        # Use the built in venv for linux builds

         - os:             linux
           sudo:           required
           python:         "3.6"
           dist:           xenial
           before_install:
             - sudo apt-get install libssl1.0.0
#             - sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
#             - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
#             - gpg -a --export E084DAB9 | sudo apt-key add -
             - sudo apt-get update -qq
             - sudo apt-get -y --no-install-recommends install r-base build-essential gcc g++ gfortran libblas-dev liblapack-dev libncurses5-dev libreadline-dev libjpeg-dev libpcre3-dev libpng-dev zlib1g-dev libbz2-dev liblzma-dev libgit2-dev libssh2-1-dev
             #- pip install pip -U
             - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
             - python3 get-pip.py --force-reinstall


         - os:             linux
           sudo:           required
           python:         "3.7"
           dist:           xenial
           before_install:
             - sudo apt-get install libssl1.0.0
#             - sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
#             - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
#             - gpg -a --export E084DAB9 | sudo apt-key add -
             - sudo apt-get update -qq
             - sudo apt-get -y --no-install-recommends install r-base build-essential gcc g++ gfortran libblas-dev liblapack-dev libncurses5-dev libreadline-dev libjpeg-dev libpcre3-dev libpng-dev zlib1g-dev libbz2-dev liblzma-dev libgit2-dev libssh2-1-dev
             - pip install pip -U


         - os:             linux
           sudo:           required
           python:         "3.8"
           dist:           xenial
           before_install:
             - sudo apt-get install libssl1.0.0
#             - sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
#             - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
#             - gpg -a --export E084DAB9 | sudo apt-key add -
             - sudo apt-get update -qq
             - sudo apt-get -y --no-install-recommends install r-base build-essential gcc g++ gfortran libblas-dev liblapack-dev libncurses5-dev libreadline-dev libjpeg-dev libpcre3-dev libpng-dev zlib1g-dev libbz2-dev liblzma-dev libgit2-dev libssh2-1-dev
             - pip install pip -U


env:
  - TRAVISBUILD="True", INSTALL_R_PACKAGES=True

install:
 # - pip3 install . --upgrade --force -v
  - pip install -U git+https://github.com/dieterich-lab/circtools.git@devel

script:
    - circtools --version
#    - ./tests/01_test_dcc.sh
#    - ./tests/02_test_quickcheck.sh