name: Multi-arch Docker Container

on:
  workflow_run:
    workflows: ["circtools CI"]
    types:
      - completed

jobs:
  build-and-push:
    name: Build multiarch Docker image and push to repositories
    runs-on: ubuntu-latest
    steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v2
          - name: Login to Github Packages
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and Push image
          run: |
            docker buildx build \
              --file ./docker/Dockerfile \
              --platform linux/arm64,linux/amd64\
              --tag ghcr.io/jakobilab/circtools/circtools:latest \
              --push .