name: Circtools CI

on:
  push:
  pull_request:
#  schedule:
#    - cron: '0 7 * * *'

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  Main:
    strategy:
      matrix:
#        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, macos-11, macos-12]
#        R: ['4.1.0' , '4.2.0' ]
#        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-22.04]
        R: ['4.2.0' ]
        python-version: ["3.10"]
    name: R ${{ matrix.R }} | Python ${{ matrix.python-version }} | ${{ matrix.os }}
    steps:
    - name: Create files
      uses: actions/checkout@v3
      with:
       ref: devel
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.R }}
    - name: Set up R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: |
          local::contrib/circtest
          local::contrib/primex
    - name: Checking library loading
      run: Rscript -e 'library(primex)'
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - name: Updating setuptools
      run: |
         python3 -m pip install -U pip setuptools
    - name: Updating pip
      run: |
         python3 -m pip install --upgrade pip
    - name: Installing circtools & Python dependencies
      run: |
         python3 -m pip install ./
         circtools --version
         which circtools
    - name: Check if circtools starts
      run: |
         circtools --version
    - name: Downloading circtools detect test data
      run: |
         wget https://arizona.box.com/shared/static/0wsx9py8w4unot7pslx6uavjpqp62vrf.bz2 -O circtools_detect_ci_input_data.tar.bz2
         tar xvf circtools_detect_ci_input_data.tar.bz2
         cd circtools_detect_ci_input_data
         pwd














    runs-on: ${{ matrix.os }}
